---
title: "Data 605 Discussion 14 Problem  Exercise 8.8 # 29"
author: "Tage N Singh"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output:
  prettydoc::html_pretty:
    theme: cayman
    highlight: github
---



---

File Locations:

<a href="https://rpubs.com/tagensingh/sps-data-605-discussion-14">R Pubs Output</a>

<a href="https://raw.githubusercontent.com/tagensingh/sps_605_wk_14/main/TSingh_Data605_discussion14.Rmd">RMD on Github</a>

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```

---


Assignment :

Pick any exercise in 8.8 of the calculus textbook.  Solve and post your solution.  If you have issues doing so, discuss them.

**Exercise 8.8 # 29**

Find the Taylor Series for the given Function :

$f(x) = e^{x} sin x$ (only find the first 4 terms)

**Solution**

From Theorem 8.8.2

For Functions $f(x) = \sum_{n = 0 }^{\infty} a_{n}x^{n}$   ----    and   ----  $g(x) = \sum_{n = 0 }^{\infty} b_{n}x^{n}$

<br>

$f(x) \ g(x)$ is given as $f(x) \ g(x) = \left( \sum_{n = 0 }^{\infty} a_{n}x^{n} \right) \left( \sum_{n = 0 }^{\infty} b_{n}x^{n} \right)$

<br>

$\implies \sum_{n = 0 }^{\infty} \left(a_{0}b_{n} + a_{1}b_{n-1} +...a_{n}b_{0}\right) x^{n} \ for \left| x \right| \lt R$

<br>

---

The Taylor Series for $f(x) = e^{x} = \sum_{n = 0}^{\infty}\frac{x^{n}}{n!}$  --  The Interval of convergence is $\left( -\infty, \infty   \right)$

<br>

The first 5 terms are given as : - $1 + x + \frac{x^{2}}{2!} + \frac{x^{3}}{3!} + \frac{x^{4}}{4!}$

---

<br>

The Taylor Series for $f(x) = sin x = \sum_{n = 0}^{\infty}(-1^{n})\frac{x^{2n+1}}{(2n+1)!}$  --  The Interval of convergence is $\left( -\infty, \infty   \right)$

<br>

The first 5 terms are given as : - $x -\frac{x^{3}}{3!} + \frac{x^{5}}{5!} - \frac{x^{7}}{7!} + \frac{x^{9}}{9!}$

---

Applying Theorem 8.8.2  - Using only the first 4 terms of each function as required :

$f(x) = e^{x} sin x$ = $\left(1 + x + \frac{x^{2}}{2!} + \frac{x^{3}}{3!}\right)  \left(x -\frac{x^{3}}{3!} + \frac{x^{5}}{5!} - \frac{x^{7}}{7!} \right)$

Using the Distributive Law to Distribute the right hand expression across the left :

$$
1 * \left(x -\frac{x^{3}}{3!} + \frac{x^{5}}{5!} - \frac{x^{7}}{7!} \right) 
+ \frac{x^{2}}{2!} * \left(x -\frac{x^{3}}{3!} + \frac{x^{5}}{5!} - \frac{x^{7}}{7!} \right)
+ \frac{x^{3}}{3!} * \left(x -\frac{x^{3}}{3!} + \frac{x^{5}}{5!} - \frac{x^{7}}{7!} \right)
+ \frac{x^{4}}{4!} * \left(x -\frac{x^{3}}{3!} + \frac{x^{5}}{5!} - \frac{x^{7}}{7!} \right)
$$

$\implies$

$$
x -\frac{x^{3}}{3!} + \frac{x^{5}}{5!} - \frac{x^{7}}{7!}
+ \frac{x^{3}}{2!} -\frac{x^{5}}{3! * 2!} + \frac{x^{7}}{2! * 5!} - \frac{x^{9}}{2! * 7!}
+ \frac{x^{4}}{3!} -\frac{x^{6}}{3! * 3!} + \frac{x^{8}}{3! * 5!} - \frac{x^{10}}{3! * 7!}
+ \frac{x^{5}}{4!} -\frac{x^{7}}{4! * 3!} + \frac{x^{9}}{4! * 5!} - \frac{x^{11}}{4! * 7!}
$$

<br>

If we expand the first 4 terms, we get :

$x -\frac{x^{3}}{6} + \frac{x^{5}}{60} - \frac{x^{7}}{5040}$ 


The combined Series Converge on $\left( -\infty, \infty   \right)$ 


since each of the individual functions converge on $\left( -\infty, \infty   \right)$.


Note : that the first 4 terms of the combined functions $f(x) = e^{x} sin x$ is the same as the first 4 terms for $f(x) = sin x$


---

<br>

**References**

https://latexeditor.lagrida.com/

https://bookdown.org/yihui/rmarkdown-cookbook/
